rule "Reworked by FRNathan13#1826 - Based on original 500% mode, but with some additions and fixes.":
    @Event global
    @Delimiter
    @Disabled

rule "WARNING: I do not recommend using workshop editor to modify any rule. Game crash alert!":
    @Event global
    @Delimiter
    @Disabled

rule "Instead of you can use VSCode with OverPy extension to modify rules.":
    @Event global
    @Delimiter
    @Disabled
    
rule "Source Code: https://github.com/nathan130200/NuclearWeaponsWarehouse":
    @Event global
    @Delimiter
    @Disabled

rule "----------------------------------------------------------------------------------------------------------------":
    @Event global
    @Delimiter
    @Disabled
